name: Main Workflow Runner

on:
  workflow_dispatch:
  schedule:
    # runs at 6 AM BRT (SÃ£o Paulo Time)
    - cron: "0 9 * * *"

jobs:
  call-commit-day-moment:
    uses: ./.github/workflows/commit-day-moment.yml


  call-commit-dayweek:
    needs: call-commit-day-moment
    if: always()
    uses: ./.github/workflows/commit-dayweek.yml


  call-editor-time:
    needs: call-commit-dayweek
    if: always()
    uses: ./.github/workflows/editor-time.yml


  call-lang-time:
    needs: call-editor-time
    if: always()
    uses: ./.github/workflows/lang-time.yml


  call-stats-transparent:
    needs: call-lang-time
    if: always()
    uses: ./.github/workflows/stats-transparent.yml