name: Generate repository cards

on:
  schedule:
    # runs at 5:40 AM BRT (SÃ£o Paulo Time)
    - cron: "40 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=LucasOkokama&repo=portfolio-v1&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-portfolio-v1.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/repository-cards/*.svg
          git commit -m "Update repository cards" || exit 0
          git push
