name: Generate repository cards

on:
  schedule:
    # runs at 5:40 AM BRT (SÃ£o Paulo Time)
    - cron: "40 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate portfolio-v1 card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=portfolio-v1&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-portfolio-v1.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate anime-blog-review card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=anime-blog-review&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-anime-blog-review.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate loja-vinho card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=loja-vinho&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-loja-vinho.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate pexels-image-search card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=pexels-image-search&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-pexels-image-search.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate anime-statistics-charts card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=anime-statistics-charts&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-anime-statistics-charts.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate filmes-statistics-charts card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=filmes-statistics-charts&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-filmes-statistics-charts.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate EarthWise-website card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=EarthWise-website&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-EarthWise-website.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate animals-gallery card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=animals-gallery&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-animals-gallery.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate additional design & backend cards
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=portfolio-v1-dsgn&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-portfolio-v1-dsgn.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate anime-blog-review-dsgn card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=anime-blog-review-dsgn&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-anime-blog-review-dsgn.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate wine-store-dsgn card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=wine-store-dsgn&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-wine-store-dsgn.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate pexels-image-search-dsgn card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=pexels-image-search-dsgn&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-pexels-image-search-dsgn.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate api-rest-graphql card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=api-rest-graphql&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-api-rest-graphql.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate unit-integration-test card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=unit-integration-test&hide_border=true&bg_color=141b24&title_color=ca7439&icon_color=888888&text_color=888888&description_lines_count=3
          path: assets/repository-cards/repocard-unit-integration-test.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/repository-cards/*.svg
          git commit -m "Update repository cards" || exit 0
          git push
